#index:
#    path: /
#    controller: App\Controller\DefaultController::index
Hello_page:
  path: /MainPage

  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
      template: 'Hello_page.html.twig'
app_page:
  path: /app_product_list

  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: 'new.html.twig'


